// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDR6F2eSsosPahRKdxfiGmhST0Pow22g9s',
    appId: '1:571741417959:web:1d092172851ddfd9b2cd42',
    messagingSenderId: '571741417959',
    projectId: 'fitness-nutrition-app-76e2e',
    authDomain: 'fitness-nutrition-app-76e2e.firebaseapp.com',
    storageBucket: 'fitness-nutrition-app-76e2e.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA2Kwnuj-QSxZWhJWV_KGO0IGe2G-xAdmQ',
    appId: '1:571741417959:android:8618ccb88ceb14f2b2cd42',
    messagingSenderId: '571741417959',
    projectId: 'fitness-nutrition-app-76e2e',
    storageBucket: 'fitness-nutrition-app-76e2e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA8ydy7vd1I_fHxe726IKdJfFtQtZhkhAQ',
    appId: '1:571741417959:ios:880c51fa342f20f4b2cd42',
    messagingSenderId: '571741417959',
    projectId: 'fitness-nutrition-app-76e2e',
    storageBucket: 'fitness-nutrition-app-76e2e.appspot.com',
    iosClientId: '571741417959-m6st0nosksihefgbfqndtg08ugpa0bs0.apps.googleusercontent.com',
    iosBundleId: 'com.example.fitnessApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA8ydy7vd1I_fHxe726IKdJfFtQtZhkhAQ',
    appId: '1:571741417959:ios:880c51fa342f20f4b2cd42',
    messagingSenderId: '571741417959',
    projectId: 'fitness-nutrition-app-76e2e',
    storageBucket: 'fitness-nutrition-app-76e2e.appspot.com',
    iosClientId: '571741417959-m6st0nosksihefgbfqndtg08ugpa0bs0.apps.googleusercontent.com',
    iosBundleId: 'com.example.fitnessApp',
  );
}
